name: FreeBASIC CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install System Dependencies & ZeroMQ
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make libncurses5 libffi-dev libzmq3-dev

    - name: Install FreeBASIC Compiler (fbc)
      run: |
        URL="https://sourceforge.net/projects/fbc/files/FreeBASIC-1.10.1/Binaries-Linux/FreeBASIC-1.10.1-ubuntu-22.04-x86_64.tar.gz/download"
        curl -s -L "$URL" | tar -xz
        
        cd FreeBASIC-1.10.1-ubuntu-22.04-x86_64
        sudo ./install.sh -i
        
        fbc -version

    - name: Compile FreeBasicZMQ Project
      run: |
        cd ./FreeBasicZMQ/Example
        fbc -w all Zmq.bas -x FreeBasicZMQ_Test
